# Generated by Django 2.0.4 on 2019-01-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('grade', models.IntegerField()),
                ('pro', models.IntegerField()),
                ('link', models.CharField(max_length=30)),
            ],
        ),
    ]
