# Generated by Django 2.1.5 on 2019-02-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='zadachi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulti', models.CharField(max_length=45)),
                ('text', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=45)),
                ('tags', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
    ]
