# Generated by Django 2.1.5 on 2019-02-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_zadachi'),
    ]

    operations = [
        migrations.CreateModel(
            name='foruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('zadachi', models.CharField(max_length=300)),
                ('teachers', models.CharField(max_length=300)),
                ('olimps', models.CharField(max_length=300)),
            ],
        ),
    ]
