# Generated by Django 2.1.5 on 2019-03-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_foruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField()),
                ('students', models.CharField(max_length=100000)),
                ('name', models.CharField(max_length=30)),
                ('Theme', models.CharField(max_length=30)),
                ('other', models.CharField(max_length=100)),
            ],
        ),
    ]
