# Generated by Django 2.1.5 on 2019-03-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zadachi',
            name='text',
            field=models.CharField(max_length=20000),
        ),
    ]
