# Generated by Django 2.1.5 on 2019-08-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ava',
            field=models.CharField(default='tek', max_length=100000),
            preserve_default=False,
        ),
    ]
