# Generated by Django 2.1.5 on 2019-05-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('blocks', models.CharField(max_length=10000000)),
                ('blocks_inner', models.CharField(max_length=100000000000000000000000000000)),
            ],
        ),
        migrations.CreateModel(
            name='Teo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000000000000000000000000)),
            ],
        ),
    ]
